<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lewdventure.Server.Battle" />
    <InternalsVisibleTo Include="Lewdventure.Server.Infrastructure" />
    <InternalsVisibleTo Include="Lewdventure.Server.Api" />
    <InternalsVisibleTo Include="Lewdventure.Server.GoldenTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.UnitTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.IntegrationTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.Benchmarks" />
    <InternalsVisibleTo Include="Lewdventure.Server.ConfigTool" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
