<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lewdventure.Server.Battle" />
    <InternalsVisibleTo Include="Lewdventure.Server.Api" />
    <InternalsVisibleTo Include="Lewdventure.Server.Runs" />
    <InternalsVisibleTo Include="Lewdventure.Server.GoldenTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.UnitTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.IntegrationTests" />
    <InternalsVisibleTo Include="Lewdventure.Server.Benchmarks" />
    <InternalsVisibleTo Include="Lewdventure.Server.ConfigTool" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
