services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      DOTNET_gcServer: "0"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  config-tool:
    environment:
      DOTNET_ENVIRONMENT: Staging

  mongo:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 768M
