namespace Server.Battles
{
    internal sealed class CharacteristicBuckets
    {
        public float HealthBase;
        public float HealthLocal;
        public float HealthMinor;
        public float HealthMajor;
        public float HealthPerk;
        public float DamageBase;
        public float DamageLocal;
        public float DamageMinor;
        public float DamageMajor;
        public float DamagePerk;
        public float AttackMultiplierBase;
        public float AttackMultiplierLocal;
        public float AttackMultiplierPerk;
        public float DefenceBase;
        public float DefenceLocal;
        public float DefencePerk;
        public float DefenceCoefficient;
        public float EvasionBase;
        public float EvasionLocal;
        public float EvasionPerk;
        public float CriticalChanceBase;
        public float CriticalChanceLocal;
        public float CriticalChancePerk;
        public float CriticalMultiplierBase;
        public float CriticalMultiplierLocal;
        public float CriticalMultiplierPerk;
        public float Combo1ChanceBase;
        public float Combo1ChanceLocal;
        public float Combo1ChancePerk;
        public float Combo2ChanceBase;
        public float Combo2ChanceLocal;
        public float Combo2ChancePerk;
        public float Combo1MultiplierBase;
        public float Combo1MultiplierLocal;
        public float Combo1MultiplierPerk;
        public float Combo2MultiplierBase;
        public float Combo2MultiplierLocal;
        public float Combo2MultiplierPerk;
        public float CounterChanceBase;
        public float CounterChanceLocal;
        public float CounterChancePerk;
        public float CounterMultiplierBase;
        public float CounterMultiplierLocal;
        public float CounterMultiplierPerk;
        public float SkillMultiplierBase;
        public float SkillMultiplierLocal;
        public float SkillMultiplierPerk;
        public float EnergyBase;
        public float EnergyLocal;
        public float EnergyPerk;
        public float EnergyMaxBase;
        public float VampyrismBase;
        public float VampyrismLocal;
        public float VampyrismPerk;
        public float HealingBoostBase;
        public float HealingBoostLocal;
        public float HealingBoostPerk;

        public CharacteristicBuckets Clone()
        {
            return new CharacteristicBuckets
            {
                HealthBase = HealthBase,
                HealthLocal = HealthLocal,
                HealthMinor = HealthMinor,
                HealthMajor = HealthMajor,
                HealthPerk = HealthPerk,
                DamageBase = DamageBase,
                DamageLocal = DamageLocal,
                DamageMinor = DamageMinor,
                DamageMajor = DamageMajor,
                DamagePerk = DamagePerk,
                AttackMultiplierBase = AttackMultiplierBase,
                AttackMultiplierLocal = AttackMultiplierLocal,
                AttackMultiplierPerk = AttackMultiplierPerk,
                DefenceBase = DefenceBase,
                DefenceLocal = DefenceLocal,
                DefencePerk = DefencePerk,
                DefenceCoefficient = DefenceCoefficient,
                EvasionBase = EvasionBase,
                EvasionLocal = EvasionLocal,
                EvasionPerk = EvasionPerk,
                CriticalChanceBase = CriticalChanceBase,
                CriticalChanceLocal = CriticalChanceLocal,
                CriticalChancePerk = CriticalChancePerk,
                CriticalMultiplierBase = CriticalMultiplierBase,
                CriticalMultiplierLocal = CriticalMultiplierLocal,
                CriticalMultiplierPerk = CriticalMultiplierPerk,
                Combo1ChanceBase = Combo1ChanceBase,
                Combo1ChanceLocal = Combo1ChanceLocal,
                Combo1ChancePerk = Combo1ChancePerk,
                Combo2ChanceBase = Combo2ChanceBase,
                Combo2ChanceLocal = Combo2ChanceLocal,
                Combo2ChancePerk = Combo2ChancePerk,
                Combo1MultiplierBase = Combo1MultiplierBase,
                Combo1MultiplierLocal = Combo1MultiplierLocal,
                Combo1MultiplierPerk = Combo1MultiplierPerk,
                Combo2MultiplierBase = Combo2MultiplierBase,
                Combo2MultiplierLocal = Combo2MultiplierLocal,
                Combo2MultiplierPerk = Combo2MultiplierPerk,
                CounterChanceBase = CounterChanceBase,
                CounterChanceLocal = CounterChanceLocal,
                CounterChancePerk = CounterChancePerk,
                CounterMultiplierBase = CounterMultiplierBase,
                CounterMultiplierLocal = CounterMultiplierLocal,
                CounterMultiplierPerk = CounterMultiplierPerk,
                SkillMultiplierBase = SkillMultiplierBase,
                SkillMultiplierLocal = SkillMultiplierLocal,
                SkillMultiplierPerk = SkillMultiplierPerk,
                EnergyBase = EnergyBase,
                EnergyLocal = EnergyLocal,
                EnergyPerk = EnergyPerk,
                EnergyMaxBase = EnergyMaxBase,
                VampyrismBase = VampyrismBase,
                VampyrismLocal = VampyrismLocal,
                VampyrismPerk = VampyrismPerk,
                HealingBoostBase = HealingBoostBase,
                HealingBoostLocal = HealingBoostLocal,
                HealingBoostPerk = HealingBoostPerk,
            };
        }
    }
}
