name: rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - dev
          - stage
          - prod
      image_tag:
        type: string
        required: false
        default: ""

permissions:
  contents: read

jobs:
  rollback:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: ${{ inputs.environment }}
      image_tag: ${{ inputs.image_tag || 'rollback' }}
    secrets: inherit
